name: Main build

on:
  push:
    branches:
      - master
      - 'release/**'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Node.js version #https://github.com/actions/setup-node/pull/338
        id: nvm
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          cache: 'yarn'
      - name: Install modules
        run: yarn install
      - name: Compile
        run: yarn build
      - name: Run tests
        run: yarn test:coverage
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/lcov.info

  release-draft:
    name: Release Draft
    runs-on: ubuntu-latest
    steps:
      - name: Prepare release draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
